<?php

use Illuminate\Database\Seeder;

class CategoriesFeaturesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('category_features')->insert([
            [ 'winner' => false, 'feature_id' => 1, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 2, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 4, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 5, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 6, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 7, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 9, 'category_id' => 1 ],
            [ 'winner' => false, 'feature_id' => 60, 'category_id' => 2 ],
            [ 'winner' => false, 'feature_id' => 61, 'category_id' => 2 ],
            [ 'winner' => false, 'feature_id' => 62, 'category_id' => 2 ],
            [ 'winner' => false, 'feature_id' => 63, 'category_id' => 2 ],
            [ 'winner' => false, 'feature_id' => 64, 'category_id' => 2 ],
            [ 'winner' => false, 'feature_id' => 65, 'category_id' => 3 ],
            [ 'winner' => false, 'feature_id' => 66, 'category_id' => 3 ],
            [ 'winner' => false, 'feature_id' => 67, 'category_id' => 3 ],
            [ 'winner' => false, 'feature_id' => 68, 'category_id' => 3 ],
            [ 'winner' => false, 'feature_id' => 69, 'category_id' => 3 ],
            [ 'winner' => false, 'feature_id' => 70, 'category_id' => 4 ],
            [ 'winner' => false, 'feature_id' => 71, 'category_id' => 4 ],
            [ 'winner' => false, 'feature_id' => 72, 'category_id' => 4 ],
            [ 'winner' => false, 'feature_id' => 73, 'category_id' => 4 ],
            [ 'winner' => false, 'feature_id' => 74, 'category_id' => 4 ],
            [ 'winner' => false, 'feature_id' => 75, 'category_id' => 5 ],
            [ 'winner' => false, 'feature_id' => 76, 'category_id' => 5 ],
            [ 'winner' => false, 'feature_id' => 77, 'category_id' => 5 ],
            [ 'winner' => false, 'feature_id' => 78, 'category_id' => 5 ],
            [ 'winner' => false, 'feature_id' => 79, 'category_id' => 5 ],
            [ 'winner' => false, 'feature_id' => 15, 'category_id' => 6 ],
            [ 'winner' => false, 'feature_id' => 16, 'category_id' => 6 ],
            [ 'winner' => false, 'feature_id' => 17, 'category_id' => 6 ],
            [ 'winner' => false, 'feature_id' => 18, 'category_id' => 6 ],
            [ 'winner' => false, 'feature_id' => 19, 'category_id' => 6 ],
            [ 'winner' => false, 'feature_id' => 20, 'category_id' => 7 ],
            [ 'winner' => false, 'feature_id' => 2, 'category_id' => 7 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 7 ],
            [ 'winner' => false, 'feature_id' => 14, 'category_id' => 7 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 7 ],
            [ 'winner' => false, 'feature_id' => 21, 'category_id' => 8 ],
            [ 'winner' => false, 'feature_id' => 2, 'category_id' => 8 ],
            [ 'winner' => false, 'feature_id' => 6, 'category_id' => 8 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 8 ],
            [ 'winner' => false, 'feature_id' => 22, 'category_id' => 8 ],
            [ 'winner' => false, 'feature_id' => 80, 'category_id' => 9 ],
            [ 'winner' => false, 'feature_id' => 81, 'category_id' => 9 ],
            [ 'winner' => false, 'feature_id' => 82, 'category_id' => 9 ],
            [ 'winner' => false, 'feature_id' => 83, 'category_id' => 9 ],
            [ 'winner' => false, 'feature_id' => 84, 'category_id' => 9 ],
            [ 'winner' => false, 'feature_id' => 23, 'category_id' => 10 ],
            [ 'winner' => false, 'feature_id' => 24, 'category_id' => 10 ],
            [ 'winner' => false, 'feature_id' => 25, 'category_id' => 10 ],
            [ 'winner' => false, 'feature_id' => 26, 'category_id' => 10 ],
            [ 'winner' => false, 'feature_id' => 27, 'category_id' => 10 ],
            [ 'winner' => false, 'feature_id' => 28, 'category_id' => 11 ],
            [ 'winner' => false, 'feature_id' => 29, 'category_id' => 11 ],
            [ 'winner' => false, 'feature_id' => 30, 'category_id' => 11 ],
            [ 'winner' => false, 'feature_id' => 31, 'category_id' => 11 ],
            [ 'winner' => false, 'feature_id' => 32, 'category_id' => 11 ],
            [ 'winner' => false, 'feature_id' => 33, 'category_id' => 12 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 12 ],
            [ 'winner' => false, 'feature_id' => 11, 'category_id' => 12 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 12 ],
            [ 'winner' => false, 'feature_id' => 9, 'category_id' => 12 ],
            [ 'winner' => false, 'feature_id' => 34, 'category_id' => 13 ],
            [ 'winner' => false, 'feature_id' => 35, 'category_id' => 13 ],
            [ 'winner' => false, 'feature_id' => 36, 'category_id' => 13 ],
            [ 'winner' => false, 'feature_id' => 37, 'category_id' => 13 ],
            [ 'winner' => false, 'feature_id' => 38, 'category_id' => 13 ],
            [ 'winner' => false, 'feature_id' => 2, 'category_id' => 14 ],
            [ 'winner' => false, 'feature_id' => 22, 'category_id' => 14 ],
            [ 'winner' => false, 'feature_id' => 39, 'category_id' => 14 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 15 ],
            [ 'winner' => false, 'feature_id' => 6, 'category_id' => 15 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 15 ],
            [ 'winner' => false, 'feature_id' => 40, 'category_id' => 15 ],
            [ 'winner' => false, 'feature_id' => 9, 'category_id' => 15 ],
            [ 'winner' => false, 'feature_id' => 14, 'category_id' => 16 ],
            [ 'winner' => false, 'feature_id' => 1, 'category_id' => 16 ],
            [ 'winner' => false, 'feature_id' => 17, 'category_id' => 16 ],
            [ 'winner' => false, 'feature_id' => 41, 'category_id' => 16 ],
            [ 'winner' => false, 'feature_id' => 42, 'category_id' => 16 ],
            [ 'winner' => false, 'feature_id' => 21, 'category_id' => 17 ],
            [ 'winner' => false, 'feature_id' => 20, 'category_id' => 17 ],
            [ 'winner' => false, 'feature_id' => 2, 'category_id' => 17 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 17 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 17 ],
            [ 'winner' => false, 'feature_id' => 43, 'category_id' => 18 ],
            [ 'winner' => false, 'feature_id' => 44, 'category_id' => 18 ],
            [ 'winner' => false, 'feature_id' => 45, 'category_id' => 18 ],
            [ 'winner' => false, 'feature_id' => 46, 'category_id' => 18 ],
            [ 'winner' => false, 'feature_id' => 47, 'category_id' => 18 ],
            [ 'winner' => false, 'feature_id' => 48, 'category_id' => 19 ],
            [ 'winner' => false, 'feature_id' => 49, 'category_id' => 19 ],
            [ 'winner' => false, 'feature_id' => 50, 'category_id' => 19 ],
            [ 'winner' => false, 'feature_id' => 51, 'category_id' => 19 ],
            [ 'winner' => false, 'feature_id' => 52, 'category_id' => 19 ],
            [ 'winner' => false, 'feature_id' => 33, 'category_id' => 20 ],
            [ 'winner' => false, 'feature_id' => 20, 'category_id' => 20 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 20 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 20 ],
            [ 'winner' => false, 'feature_id' => 40, 'category_id' => 20 ],
            [ 'winner' => false, 'feature_id' => 33, 'category_id' => 21 ],
            [ 'winner' => false, 'feature_id' => 20, 'category_id' => 21 ],
            [ 'winner' => false, 'feature_id' => 3, 'category_id' => 21 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 21 ],
            [ 'winner' => false, 'feature_id' => 40, 'category_id' => 21 ],
            [ 'winner' => false, 'feature_id' => 20, 'category_id' => 22 ],
            [ 'winner' => false, 'feature_id' => 53, 'category_id' => 22 ],
            [ 'winner' => false, 'feature_id' => 54, 'category_id' => 22 ],
            [ 'winner' => false, 'feature_id' => 40, 'category_id' => 22 ],
            [ 'winner' => false, 'feature_id' => 55, 'category_id' => 22 ],
            [ 'winner' => false, 'feature_id' => 1, 'category_id' => 23 ],
            [ 'winner' => false, 'feature_id' => 56, 'category_id' => 23 ],
            [ 'winner' => false, 'feature_id' => 57, 'category_id' => 23 ],
            [ 'winner' => false, 'feature_id' => 58, 'category_id' => 23 ],
            [ 'winner' => false, 'feature_id' => 14, 'category_id' => 23 ],
            [ 'winner' => false, 'feature_id' => 59, 'category_id' => 24 ],
            [ 'winner' => false, 'feature_id' => 4, 'category_id' => 24 ],
            [ 'winner' => false, 'feature_id' => 5, 'category_id' => 24 ],
            [ 'winner' => false, 'feature_id' => 8, 'category_id' => 24 ],
            [ 'winner' => false, 'feature_id' => 9, 'category_id' => 24 ],
        ]);
    }
}
